version: "3.7"
services:
  website:
    hostname: website
    image:  php:apache
    container_name: "website"
    environment:
      USERNAME: "toto"
      PASSWORD: "python"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - api
    networks:
      - student
    ports:
      - 8080:80
    
  api:
    hostname: api
    image: student-api:V1
    container_name: "api"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - 4000:5000
    networks:
      - student

networks:
  student:
    name: student
    