version: "3.7"
services:
  website:
    hostname: student-website
    image:  php:apache
    container_name: "student-website"
    environment:
      USERNAME: "toto"
      PASSWORD: "python"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - student-api
    networks:
      - pozos
    ports:
      - 8080:80
    
  student-api:
    hostname: student-api
    image: student-api:v1
    container_name: "student-api"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - 4000:5000
    networks:
      - student
    depends_on:
      - build-image

  build-image:
    build:
      context: ./simple_api/
      dockerfile: Dockerfile
    volumes:
      - ./student_age.json:/data/student_age.json
    networks:
      - student

networks:
  student:
    name: student
    